server:
  port: 8090

spring:
  application:
    name: eureka

eureka:
      instance:
        hostname: localhost
        lease-expiration-duration-in-seconds: 5
        lease-renewal-interval-in-seconds: 5
      client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
                defaultZone: http://localhost:8090/eureka/
      server:
        enable-self-preservation: false

endpoints:
     shutdown:
      enabled: true